### PR TITLE
Force regenerate

### PR DESCRIPTION
**Pull request by NickOrtiz**
Adding force option and setting needs_regeneration variable to true if flag is being used. 
Hoping I read the requirements for issue #63 correctly.

### CODE REVIEW

**Comment by selrond** [comment]
So what's happened to this one?

**Comment by NickOrtiz** [comment]
I pulled the trigger early before properly reviewing it. You asked a good time, I can review it this evening and see if my previous commits make any sense.

**Comment by selrond** [comment]
That'd be awesome! thanks

**Comment by NickOrtiz** [comment]
re-opening now to iterate upon

**Comment by NickOrtiz** [comment]
@selrond took a look and applied a fix the other day. Everything seems to make sense to me, the CI passed, etc.

**Comment by gitlost** [comment]
My sincere apologies @NickOrtiz , I'm struggling to come up with a use case for this. Will check it properly tomorrow.

**Comment by NickOrtiz** [comment]
No need to apologize and no rush on my end. I completely understand.

**Comment by schlessera** [comment]
The code path should be covered by a test. This needs such a "use case" of course.

@gitlost It was probably meant to solve a specific problem at some point, wasn't it? What was that problem?

**Comment by gitlost** [comment]
Yes, tracked it down and will address it in https://github.com/wp-cli/media-command/pull/69

So will close this and https://github.com/wp-cli/media-command/issues/63 as unneeded.

**Pull request closed without merging**
