### PR TITLE
Fix incorrect image sizes in media image-size command

### PR DESCRIPTION
**Pull request by ernilambar**
Fixes https://github.com/wp-cli/media-command/issues/116

* Uses `wp_get_registered_image_subsizes()` for fetching image size information

### CODE REVIEW

**Comment by swissspidy** [comment]
Can we add a test verifying this behavior? Should be possible to add & activate a small plugin that registers additional image sizes, then run the command.

**Comment by ernilambar** [comment]
@swissspidy Can you please run Behat test manually in GitHub action?

**Comment by swissspidy** [comment]
Oh, looks like the workflow was disabled due to inactivity

**Comment by ernilambar** [comment]
CC @danielbachhuber

**Review by schlessera — APPROVED** [review]

**Comment by schlessera** [comment]
Thanks, @ernilambar !

**Pull request merged**
