### PR TITLE
Optimize memory consumption of querying attachments

### LINKED ISSUE #134: This script times out on installs with large number of attachments
https://github.com/wp-cli/media-command/blob/830e72a2cbd3eeec95a97df2c1c17d925d86790d/src/Media_Command.php#L910

I used this script a few months ago on an install with somewhere around 12k attachments. I updated the theme and needed to resize all of my images. I initially used Regenerate Thumbnails but that timed out my login session and failed after a while. I then used this script which went a little faster but ultimately timed out and failed. I didn't think much of it then and kept running the script to see if I could make it all the way through my images.

Now that I am building a command for another client and using this script as an example, I am starting to think more about the WP_Query that gets all posts. To make this more scalable, should this query be changed to a paged query inside a foreach loop based on the number of total posts for this post type?

Something like 

```
$total = 0;
$count = wp_count_posts( 'attachment' );
		
if ( ! empty( $count ) ) {

	foreach( $count as $post_status => $posts ) {
		$total += $posts;
	}
			
}

$posts_per_page = 100;

$pages = ceil( $total / $posts_per_page );

for($page = 1; $page <= $pages; $page++) {

	$query = new WP_Query(
		array(
			'post_type'           => 'attachment',
			'post_status'        => 'any',
			'posts_per_page' => $posts_per_page,
			'paged' 		     => $page
		)
	);

        // Do loop here.

}
```

### PR DESCRIPTION
**Pull request by oxyc**
See #134

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@oxyc Just to confirm, this improved memory management in your testing?

**Comment by oxyc** [comment]
I actually haven’t completed the whole run yet but with 550k attachments the initial query ran out of memory (with full post objects) while this one handled it. But since I haven’t completed a full run yet I cant vouch that there arent any memory leaks within the regeneration loop

I can return to comment once Ive cometed the run so I can confirm whether it needs further cache suspensions or if this handles it.

**Comment by oxyc** [comment]
I ran this patch successfully on a site with 25k images. I just started the regeneration task on a site with 550k images but it will take a few days to complete before I can confirm it conclusively.

What I do know that before this patch, the get_images() query ran out of memory, which this patch fixed. I'll report back when the regenerate task finishes so I can confirm there are no memory leaks.

**Comment by danielbachhuber** [comment]
> I'll report back when the regenerate task finishes so I can confirm there are no memory leaks before closing #134 as fixed.

Sounds great, thanks!

**Review by danielbachhuber — APPROVED** [review]

**Comment by oxyc** [comment]
It's been running for 3 days now so pretty confident there are no memory leaks in the loop.

**Comment by danielbachhuber** [comment]
@oxyc Awesome — thanks for reporting back!

**Pull request merged**
