### PR TITLE
Get custom image sizes only once with the correct info

### LINKED ISSUE #116: Image-Size list shows custom image sizes twice
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The custom image sizes are listed twice. Once with the correct information and once with the height and width missing.

```
+-----------------------+-------+--------+------+-------+
| name                  | width | height | crop | ratio |
+-----------------------+-------+--------+------+-------+
| full                  |       |        | N/A  | N/A   |
| large                 | 1024  | 1024   | soft | N/A   |
| medium_large          | 768   | 0      | soft | N/A   |
| medium                | 300   | 300    | soft | N/A   |
| mini-profile-thumb    | 220   | 220    | soft | N/A   |
| thumbnail             | 150   | 150    | hard | 1:1   |
| mini-navigation-thumb | 150   | 20     | soft | N/A   |
| edit-screen-thumb     | 120   | 120    | soft | N/A   |
| mini-frontpage-thumb  | 100   | 50     | soft | N/A   |
| edit-screen-thumb     | 0     | 0      | soft | N/A   |
| mini-profile-thumb    | 0     | 0      | soft | N/A   |
| mini-navigation-thumb | 0     | 0      | soft | N/A   |
| mini-frontpage-thumb  | 0     | 0      | soft | N/A   |
+-----------------------+-------+--------+------+-------+
```

**Describe how other contributors can replicate this bug**

- Register a custom image size `add_image_size( 'mini-profile-thumb', 220, 220 );`
- `wp media image-size`
- See results

**Describe what you would expect as the correct outcome**

I expect the result to look as follows

```
+-----------------------+-------+--------+------+-------+
| name                  | width | height | crop | ratio |
+-----------------------+-------+--------+------+-------+
| full                  |       |        | N/A  | N/A   |
| large                 | 1024  | 1024   | soft | N/A   |
| medium_large          | 768   | 0      | soft | N/A   |
| medium                | 300   | 300    | soft | N/A   |
| mini-profile-thumb    | 220   | 220    | soft | N/A   |
| thumbnail             | 150   | 150    | hard | 1:1   |
| mini-navigation-thumb | 150   | 20     | soft | N/A   |
| edit-screen-thumb     | 120   | 120    | soft | N/A   |
| mini-frontpage-thumb  | 100   | 50     | soft | N/A   |
+-----------------------+-------+--------+------+-------+
```

**Let us know what environment you are running this on**

```
OS:	Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64
Shell:
PHP binary:	/usr/local/bin/php
PHP version:	7.1.32
php.ini used:	/usr/local/etc/php/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/app
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:	/app/wp-cli.yml
WP-CLI version:	2.3.0
WordPress version: 5.2.4
```

**Provide a possible solution**

The code in the developer handbook is a good solution https://developer.wordpress.org/reference/functions/get_intermediate_image_sizes/#comment-730

### PR DESCRIPTION
**Pull request by grappler**
fixes #116 

Need to figure out to test it locally.

### CODE REVIEW

**Comment by schlessera** [comment]
This code currently throws errors when you run the image size tests:

Image 2019-11-11 at 12 24 43 PM

In terms of adding specific testing, I think we'd need to extend the following code to support a `STDOUT should be a table not containing rows` step: https://github.com/wp-cli/wp-cli-tests/blob/f75bae4bcd092e504f0f6101ee4632cb99f4c3eb/features/steps/then.php#L51-L64

Not sure it can be adapted or needs to be duplicated and modified.

**Comment by schlessera** [comment]
Another way of testing could be to run the command again with `--format=csv` or `format=json`, as you can then use a string check to make sure a certain size combination is not present.

**Comment by schlessera** [comment]
@grappler Still interested in getting this across the line?

**Comment by pmbaldha** [comment]
@schlessera @grappler I have fixed it in the https://github.com/wp-cli/media-command/pull/126 by changing only one file.

**Pull request closed without merging**
